services:
  sigva-front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SIGVA_BACK_URL=${VITE_SIGVA_BACK_URL:-http://localhost:8002}
        - VITE_SSO_FRONT_URL=${VITE_SSO_FRONT_URL:-http://localhost:9000}
        - VITE_SISPO_FRONT_URL=${VITE_SISPO_FRONT_URL:-http://localhost:9001}
        - VITE_SHARED_ASSET_URL=${VITE_SHARED_ASSET_URL:-http://localhost:8000}
    container_name: sigva-frontend
    restart: unless-stopped
    ports:
      - "9002:9002"
